server:
  port: 88
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: push
          uri: lb://push
          predicates:
            - Path=/api/push/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}